// <auto-generated />
using System;
using InfoTrack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfoTrack.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622081919_AddSightingTier")]
    partial class AddSightingTier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfoTrack.Infrastructure.Persistence.FirmEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EnquiryUrl")
                        .HasColumnType("text");

                    b.Property<string>("FirmName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .HasColumnType("text");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text");

                    b.Property<string>("Town")
                        .HasColumnType("text");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityKey")
                        .IsUnique();

                    b.ToTable("Firms");
                });

            modelBuilder.Entity("InfoTrack.Infrastructure.Persistence.LocationOutcomeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("SearchRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SearchRunId");

                    b.ToTable("LocationOutcomes");
                });

            modelBuilder.Entity("InfoTrack.Infrastructure.Persistence.SearchRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaOfLaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedLocations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalLocations")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUniqueFirms")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RunAtUtc");

                    b.ToTable("SearchRuns");
                });

            modelBuilder.Entity("InfoTrack.Infrastructure.Persistence.SightingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirmId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationOutcomeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.HasIndex("LocationOutcomeId");

                    b.ToTable("Sightings");
                });

            modelBuilder.Entity("InfoTrack.Infrastructure.Persistence.LocationOutcomeEntity", b =>
                {
                    b.HasOne("InfoTrack.Infrastructure.Persistence.SearchRunEntity", "SearchRun")
                        .WithMany("Locations")
                        .HasForeignKey("SearchRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchRun");
                });

            modelBuilder.Entity("InfoTrack.Infrastructure.Persistence.SightingEntity", b =>
                {
                    b.HasOne("InfoTrack.Infrastructure.Persistence.FirmEntity", "Firm")
                        .WithMany("Sightings")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfoTrack.Infrastructure.Persistence.LocationOutcomeEntity", "LocationOutcome")
                        .WithMany("Sightings")
                        .HasForeignKey("LocationOutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firm");

                    b.Navigation("LocationOutcome");
                });

            modelBuilder.Entity("InfoTrack.Infrastructure.Persistence.FirmEntity", b =>
                {
                    b.Navigation("Sightings");
                });

            modelBuilder.Entity("InfoTrack.Infrastructure.Persistence.LocationOutcomeEntity", b =>
                {
                    b.Navigation("Sightings");
                });

            modelBuilder.Entity("InfoTrack.Infrastructure.Persistence.SearchRunEntity", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
