### REST Client extension is required: https://marketplace.visualstudio.com/items?itemName=humao.rest-client 
### baseUrl comes from "rest-client.environmentVariables"
### Environments are defined in .vscode/settings.json
### switch environment using shortcut Ctrl+Alt+E(Cmd+Alt+E for macOS), or press F1 and then select/type Rest Client: Switch Environment

### Health check
GET {{baseUrl}}/health

###

### Get supported locations
GET {{baseUrl}}/api/locations
Accept: application/json

###

### Run search - multiple locations
POST {{baseUrl}}/api/searches
Content-Type: application/json

{
  "locations": ["Manchester", "Bristol", "Edinburgh", "Cardiff", "Belfast"]
}

###

### Run search - single location
POST {{baseUrl}}/api/searches
Content-Type: application/json

{
  "locations": ["London"]
}

###

### Run search - includes not found location
POST {{baseUrl}}/api/searches
Content-Type: application/json

{
  "locations": ["London", "Nowhere", "Leeds"]
}

###
